name: Python tests
run-name: Running unittests on commit ${{ github.sha }}

on:
  push:

  pull_request:

  workflow_dispatch:
    inputs:
      branch:
        type : choice 
        description: 'Select branch'
        required: true
        default: 'master'
        options:
          - 'master'
          - 'develop'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to selected branch
        uses: actions/checkout@v2  ### changing branch
        with:
          ref: ${{ github.event.inputs.branch }}
    
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest python_testing_files 

  formatting:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout to selected branch
        uses: actions/checkout@v2  ### changing branch
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run formatting
        run: |
          black python_testing_files

      - name: Run tests ### once again, to check if formatting didn't break anything
        run: |
          pytest python_testing_files 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
            commit_message: Apply automatic changes
            branch: ${{ github.head_ref }}

            # Optional git params
            commit_options: '--no-verify --signoff'

            # Optional glob pattern of files which should be added to the commit
            file_pattern: python_testing_files/*.py
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      
    

        
    